"""Persist review results.

`.ownie/state.json` is the single source of truth; `.ownie/DECISIONS.md`
is regenerated from it after every review so the two never drift.
"""

import json
import re
from datetime import date
from pathlib import Path

from ownie.models import Decision

OWNIE_DIR = Path(".ownie")
LEGACY_DIR = Path(".mentor")  # before the project was renamed to Ownie
STATE_FILE = OWNIE_DIR / "state.json"
DECISIONS_FILE = OWNIE_DIR / "DECISIONS.md"

STATUS_LABELS = {
  "owned": "✓ owned",
  "partial": "◐ partial",
  "revisit": "○ to revisit",
  "skipped": "· skipped",
  "changed": "↻ code changed",
}

LOCATION = re.compile(r"^(.+?):(\d+)(?:-(\d+))?")


def load_state():
  migrated = not OWNIE_DIR.exists() and LEGACY_DIR.is_dir()
  if migrated:
    LEGACY_DIR.rename(OWNIE_DIR)  # keep a repo's record across the rename
  if not STATE_FILE.exists():
    return {"last_reviewed_commit": None, "pending": [], "decisions": {}}
  state = json.loads(STATE_FILE.read_text())
  if migrated:
    DECISIONS_FILE.write_text(render_decisions(state))  # refresh the old header
  return state


def save_state(state):
  OWNIE_DIR.mkdir(exist_ok=True)
  STATE_FILE.write_text(json.dumps(state, indent=2) + "\n")
  DECISIONS_FILE.write_text(render_decisions(state))


def record_result(state, decision, status, answer, scope_label):
  state["decisions"][decision.id] = {
    "decision": decision.model_dump(),
    "status": status,
    "answer": answer,
    "reviewed_at": date.today().isoformat(),
    "scope": scope_label,
    "snapshot": snapshot(decision.location),
  }


def snapshot(location):
  """The code at a decision's location, whitespace-normalised; None if unreadable."""
  match = LOCATION.match(location)
  if not match:
    return None
  path, start, end = match[1], int(match[2]), int(match[3] or match[2])
  try:
    lines = Path(path).read_text(encoding="utf-8").splitlines()
  except (OSError, UnicodeDecodeError):
    return None
  return _normalise(lines[start - 1:end]) or None


def mark_changed(state):
  """Owned decisions whose code is gone from its file become "changed"; returns them.

  Matching the snapshot anywhere in the file (not at its old line numbers)
  means code that merely moved — lines added above it — isn't flagged.
  """
  changed = []
  for entry in state["decisions"].values():
    snap = entry.get("snapshot")
    if entry["status"] != "owned" or not snap:
      continue
    path = LOCATION.match(entry["decision"]["location"])[1]
    try:
      current = _normalise(Path(path).read_text(encoding="utf-8").splitlines())
    except (OSError, UnicodeDecodeError):
      current = ""
    if snap not in current:
      entry["status"] = "changed"
      changed.append(entry["decision"]["title"])
  return changed


def _normalise(lines):
  return "\n".join(" ".join(line.split()) for line in lines if line.strip())


def known_decisions(state):
  """(id, title, status) for everything already found here, so a new review reuses ids."""
  known = [(e["decision"]["id"], e["decision"]["title"], e["status"]) for e in state["decisions"].values()]
  reviewed = state["decisions"].keys()
  known += [(d["id"], d["title"], "not asked yet") for d in state.get("pending", []) if d["id"] not in reviewed]
  return known


def ownership(state):
  """(owned, known) across every decision Ownie has found in this repo.

  "Known" includes decisions still waiting in the queue, so skipping or
  quitting never inflates the score.
  """
  reviewed = state["decisions"]
  queued = {d["id"] for d in state.get("pending", [])} - reviewed.keys()
  owned = sum(1 for entry in reviewed.values() if entry["status"] == "owned")
  return owned, len(reviewed) + len(queued)


def pending_decisions(state):
  return [Decision(**d) for d in state.get("pending", [])]


def revisit_decisions(state):
  """Reviewed but not owned yet, weakest first ("to revisit" before "partial")."""
  order = {"revisit": 0, "partial": 1}
  entries = [e for e in state["decisions"].values() if e["status"] in order]
  entries.sort(key=lambda e: order[e["status"]])
  return [Decision(**e["decision"]) for e in entries]


def render_decisions(state):
  entries = list(state["decisions"].values())
  counts = {status: sum(1 for e in entries if e["status"] == status) for status in STATUS_LABELS}

  lines = [
    "# Design Decisions",
    "",
    "Generated by `ownie review` from `.ownie/state.json`. Each entry is a",
    "design decision found in this codebase, the trade-offs behind it, and",
    "how well it's owned.",
    "",
    " · ".join(f"{STATUS_LABELS[s]}: {n}" for s, n in counts.items() if n) or "No decisions reviewed yet.",
    "",
  ]

  for entry in entries:
    d = entry["decision"]
    lines += [
      f"## {d['title']}",
      f"`{d['location']}` · {d['category']} · {STATUS_LABELS[entry['status']]} ({entry['reviewed_at']})",
      "",
      f"**Chosen:** {d['chosen']}",
      "",
      "**Alternatives:**",
      *[f"- {a}" for a in d["alternatives"]],
      "",
      "**Trade-offs:**",
      *[f"- {c}" for c in d["consequences"]],
      "",
      "**Evidence:** " + ", ".join(f"`{e}`" for e in d["evidence"]),
      "",
    ]
    if entry.get("answer"):
      label = "Your explanation" if entry["status"] == "owned" else "Your last answer"
      lines += [f"**{label}:** \"{entry['answer']}\"", ""]

  return "\n".join(lines)
